#' Runs CIBERSORT for decomposing bulk RNA-seq samples using a single cell reference
#'
#' This is a custom implementation of the algorithm described by Newman et al (Nautre Methods 12:453-457).
#' CIBERSORT is an algorithm for estimating the cell type composition of a bulk sample, given a gene expression
#' profile of the sample and a known gene expression profile for each cell type potentially contributing to the sample.
#' @param response A vector of TPM of bulk RNA-seq samples. Names correspond to genes.
#' @param features A TPM matrix representing the gene expression profiles of all cell types that
#' might contribute to the bulk samples.
#' @param transform A function to be applied to columns of exprs following normalization.
#' Defaults to no transformation since bulk RNA-seq profiles are generated by pooling up
#' RNA from constituent cell types. In the original CIBERSORT paper, a logarithmic transform was used.
#' @param usegenes A vector of genes to be used.
#' @param norm Boolean, specifying whether normalize the feature data.
#' @param nu Different values of nu to evaluate support vector regression at e1071::svm. Nu defines how
#' many support vectors (i.e. genes) to use in regression.
#' @param optim.nu In the original CIBERSORT implementation, SVR is evaluated at several values of nu and
#' the value with the best RSME is chosen. This can lead to overfitting. If \code{optim.nu} is set to \code{TRUE},
#' the value for nu is chosen by cross validation, which leads to longer runtimes.
#' @param mc.cores Number of cores used, e.g. for the parallel evaluation at different balues of nu.
#' @param ... Parameters passed to e1071::svm.
#' @return A data frame in long format suitable for plotting with ggplot2.
#' @import e1071
#' @importFrom parallel mclapply
#' @export

CIBERSORT <- function(response,
                      features = NULL,
                      transform = function(x) x,
                      usegenes = NULL,
                      norm=TRUE,
                      nu= c(0.25,0.5,0.75),
                      optim.nu =FALSE,
                      mc.cores=3, ...) {
  if(is.null(features)){
    features = read.table(file.path(system.file("extdata", package = "rMAUPS"),
              "deconv/LM22.txt"), sep = "\t", row.names = 1, header = TRUE,
              check.names = FALSE, quote = "")
  }
  if (norm) features <- apply(features, 2, function(x)
    x / mean(x) * mean(response))

  if(is.null(usegenes)){
    usegenes = intersect(rownames(features), names(response))
  }else{
    usegenes = intersect(intersect(rownames(features), names(response)), usegenes)
  }
  response <- transform(response) -> allresponse
  response <- response[usegenes]
  allresponse <- allresponse[intersect(rownames(features),names(allresponse))]
  features <- transform(features[usegenes, ])
  #
  #   features <- apply(features,2,scale)
  #   response <- scale(response)

  #proper way to choose nu
  #set up CV scheme
  if (optim.nu & length(nu)>1) {
    cvorder <- sample(1:nrow(features), nrow(features))
    cvset <- rep(c(1:5), length.out = nrow(features))
    nuerror <- sapply(nu, function(n) {
      tuning <- do.call(rbind,parallel::mclapply(1:5, function(i) {
        train <- cvorder[cvset != i]
        test <- cvorder[cvset == i]
        svr <- e1071::svm(features[train,], y = response[train], type="nu-regression", kernel="linear", nu = n,  ...)
        out <- data.frame(real = response[test],
                          predicted = predict(svr, newdata = features[test,]))
      }, mc.cores=mc.cores))
      sqrt(mean((tuning$predicted - tuning$real) ^2))
    })
    nu <- nu[which.min(nuerror)]
  }

  SVR <- parallel::mclapply(nu, function(n)
    e1071::svm(features, y = response, type="nu-regression",
               kernel="linear", nu = n,  ...))

  get_RMSE <- function(SVR, truey) {
    predicted <-   e1071:::predict.svm(SVR)
    sqrt(mean((predicted - truey) ^2))
  }
  RMSE <- sapply(SVR, get_RMSE, truey = response)
  SVR <- SVR[[which.min(RMSE)]]

  coef <- t(SVR$coefs) %*% SVR$SV
  coef[coef<0] <- 0

  #P value estimation.
  predicted <- e1071:::predict.svm(SVR)
  test_statistics <- cor(predicted , response)

  #CIBERSORT is then run on m*i to produce a vector of estimated cellular fractions, f*i. CIBERSORT determines the correlation coefficient R*i between the random mixture m*i and the reconstituted mixture, f*i ?? B. This process is repeated for I iterations (I = 500 in this work) to produce R*.

  out <- t(coef/sum(coef))
  attr(out, "p") <-  cor.test(predicted , response)$p.value
  attr(out, "SV") <- SVR$SV
  out
}


#' Runs CIBERSORT for decomposing bulk RNA-seq samples using a single cell reference
#'
#' This is a custom implementation of the algorithm described by Newman et al (Nautre Methods 12:453-457).
#' CIBERSORT is an algorithm for estimating the cell type composition of a bulk sample, given a gene expression
#' profile of the sample and a known gene expression profile for each cell type potentially contributing to the sample.
#' @param exprs A data frame or matrix of raw read counts of bulk RNA-seq samples. Column names correspond to
#' sample names, row names to genes.
#' @param ... Parameters passed to e1071::svm.
#' @return A data frame in long format suitable for plotting with ggplot2.
#' @export
#'
CIBERSORTdeconv <- function(exprs, ...) {

  res = apply(exprs, 2, function(x){
    tmp = CIBERSORT(x, ...)
    # pval = attr(tmp, "p")
    c(tmp[,1]
      # , pval=pval
      )
  })
  res = as.data.frame(res, stringsAsFactors = FALSE)
  return(res)
}
